# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome da fase')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome do projeto')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome da fase')),
                ('descricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descrição')),
                ('estado', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluido')),
                ('prazo', models.DateField(verbose_name='Prazo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Fase')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projeto'),
        ),
    ]
